source "http://rubygems.org"
gem "capybara"
gem "cucumber"
gem "cuke_sniffer"
gem "faker", "1.5.0"
gem "json"
gem "json_pure"
gem "parallel"
gem "parallel_tests"
gem "poltergeist"
gem "rake"
gem "redcarpet"
gem "rest-client"
gem "rspec"
gem "selenium-webdriver"
gem "yard-cucumber"
